jaka:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: cam_joint_1
    pid: {p: 100, i: 0.01, d: 10}

  
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: cam_joint_2
    pid: {p: 100, i: 0.01, d: 10}