jaka:
    # Publish all joint states -----------------------------------
    
    cam_joint1_position_controller:
      type: position_controllers/JointPositionController
      joint: cam_joint_1
      pid: {p: 100, i: 0.01, d: 10}
  
    
    cam_joint2_position_controller:
      type: position_controllers/JointPositionController
      joint: cam_joint_2
      pid: {p: 100, i: 0.01, d: 10}