jaka:
  arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6

    gains:
      joint_1:   {p: 100.0, i: 1.0, d: 1, i_clamp: 1.0}
      joint_2:   {p: 100.0, i: 1.0, d: 1, i_clamp: 1.0}
      joint_3:   {p: 100.0, i: 1.0, d: 1, i_clamp: 1.0}
      joint_4:   {p: 100.0, i: 1.0, d: 1, i_clamp: 1.0}
      joint_5:   {p: 100.0, i: 1.0, d: 1, i_clamp: 1.0}
      joint_6:   {p: 100.0, i: 1.0, d: 1, i_clamp: 1.0}

