jaka:
  gazebo_ros_control:
    pid_gains:
      joint_1:   {p: 1000.0, i: 1.0, d: 1, i_clamp: 1.0}
      joint_2:   {p: 1000.0, i: 1.0, d: 1, i_clamp: 1.0}
      joint_3:   {p: 1000.0, i: 1.0, d: 1, i_clamp: 1.0}
      joint_4:   {p: 1000.0, i: 1.0, d: 1, i_clamp: 1.0}
      joint_5:   {p: 1000.0, i: 1.0, d: 1, i_clamp: 1.0}
      joint_6:   {p: 1000.0, i: 1.0, d: 1, i_clamp: 1.0}

camhead:
  gazebo_ros_control:
    pid_gains:
      cam_joint_1:   {p: 1000.0, i: 1.0, d: 1, i_clamp: 1.0}
      cam_joint_2:   {p: 1000.0, i: 1.0, d: 1, i_clamp: 1.0}
